// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpINtRGcezIZIuKtyLylPpdxRo563u8TU',
    appId: '1:851829651772:web:a483dc18d2d8ebb8e3c639',
    messagingSenderId: '851829651772',
    projectId: 'offroleemployeeapp',
    authDomain: 'offroleemployeeapp.firebaseapp.com',
    storageBucket: 'offroleemployeeapp.appspot.com',
    measurementId: 'G-RBVZ24CGD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0FQm9wenTUPMIFrP8TKfd8lW2VFu1XvI',
    appId: '1:851829651772:android:3590111288c7501ee3c639',
    messagingSenderId: '851829651772',
    projectId: 'offroleemployeeapp',
    storageBucket: 'offroleemployeeapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD78lDUeqm5cP47MZSkt9MBvdJ0fNnpXtw',
    appId: '1:851829651772:ios:d62e22bcc43bfa5de3c639',
    messagingSenderId: '851829651772',
    projectId: 'offroleemployeeapp',
    storageBucket: 'offroleemployeeapp.appspot.com',
    iosBundleId: 'com.example.shaktiEmployeeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD78lDUeqm5cP47MZSkt9MBvdJ0fNnpXtw',
    appId: '1:851829651772:ios:ce72fd753c174c35e3c639',
    messagingSenderId: '851829651772',
    projectId: 'offroleemployeeapp',
    storageBucket: 'offroleemployeeapp.appspot.com',
    iosBundleId: 'com.example.shaktiEmployeeApp.RunnerTests',
  );
}
