// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSsBPYnw5Kvv9-7klCr-72EQOZAFpa68o',
    appId: '1:658928240288:web:d5f7a7553b4a345e6b6bc5',
    messagingSenderId: '658928240288',
    projectId: 'shakti-employee',
    authDomain: 'shakti-employee.firebaseapp.com',
    storageBucket: 'shakti-employee.appspot.com',
    measurementId: 'G-WDP8FV5NDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj4UHOEL-3XcaG5441Bh19pxfKGQDiRLI',
    appId: '1:658928240288:android:8505a13bb0af408f6b6bc5',
    messagingSenderId: '658928240288',
    projectId: 'shakti-employee',
    storageBucket: 'shakti-employee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy0RtoMThZeHpqS4jxraqrnJOPRiktcpI',
    appId: '1:658928240288:ios:c81f6002626f22376b6bc5',
    messagingSenderId: '658928240288',
    projectId: 'shakti-employee',
    storageBucket: 'shakti-employee.appspot.com',
    iosBundleId: 'com.example.shaktiEmployeeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy0RtoMThZeHpqS4jxraqrnJOPRiktcpI',
    appId: '1:658928240288:ios:e0dfcbd6e569f4516b6bc5',
    messagingSenderId: '658928240288',
    projectId: 'shakti-employee',
    storageBucket: 'shakti-employee.appspot.com',
    iosBundleId: 'com.example.shaktiEmployeeApp.RunnerTests',
  );
}
